# Target architecture of the UML kernel binary file. Valid values include:
# i386, ia64, ppc, and x86_64
SUBARCH?=x86_64

# Kernel release
KERNEL_RELEASE?=3.9.2

# URL of the kernel tarball, if required
KERNEL_SUFFIX?=.tar.xz
KERNEL_URL_BASE?=http://www.kernel.org/pub/linux/kernel/v3.x/linux-
KERNEL_URL=$(KERNEL_URL_BASE)$(KERNEL_RELEASE)$(KERNEL_SUFFIX)
